#!/bin/sh

#export JAVA_HOME=/home/vjovanov/bin/jdk1.7.0_51/
WARES="1" # "2 4 8 16"
SAMPLES=5

# H-Store
HLOOPS=8000000
BOOST=/usr/local/boost

# MySQL
MYUSER=root
MYPASS=ROOT
MYLOOPS=2000
MYDB=tpcctest

# VoltDB
VOLTDB=/home/vjovanov/voltdb
VTIME=60

# output format: <name>,<warehouses>,<value>,<time>

# ------------------------------------------------------------------------------
cd `dirname $0`; BENCH=`pwd`; cd ..; BASE=`pwd`
cd $BENCH; gcc -O3 t2.c -o t2;
if [ "$BOOST" ]; then export DYLD_LIBRARY_PATH=$BOOST/lib; export LD_LIBRARY_PATH=$BOOST/lib; BOOST="-I$BOOST/include -L$BOOST/lib"; fi
if [ ! -z "$MYPASS" ]; then myargs="-p$MYPASS"; fi; myargs="-u$MYUSER $myargs $MYDB"

load() { # $1=warehouses, $2=type
 myf="$BENCH/systems/tpcc/mysql/db$1$2.sql.bz2"
 mysql $myargs < $BENCH/systems/tpcc/mysql/tpcc_$2.sql
 mysql $myargs < $BENCH/systems/tpcc/mysql/tpcc_proc.sql
 if [ ! -f "$myf" ]; then
   echo "Recreating Database..."
   cd $BASE; sbt "test:run-main ddbt.tpcc.loadtest.TpccLoad -w $1 -u $MYUSER -p $MYPASS" || exit 1; cd $BENCH
   mysqldump $myargs | bzip2 > $myf
 else
   echo "Reusing Database..."
   bzcat $myf | mysql $myargs
 fi
}

case "$1" in
# ------------------------------------------------------------------------------
hstore)
  SOURCES="TupleBuffer.cpp test.cpp HashIndex.cpp UnexpectedException.cpp Exception.cpp Socket.cpp ClientSocket.cpp ServerSocket.cpp StopWatch.cpp util.cpp"
  comp() { cd "$BASE/h-store/$1"; g++ -o "$BENCH/systems/tpcc/hstore/test" -D"NUM_LOOPS=$HLOOPS" -O3 -lboost_system $BOOST $SOURCES; }
  bench() {
    cd "$BENCH";
    for W in $WARES; do
      i=0; while [ "$i" != "$SAMPLES" ]; do i="`expr $i + 1`";
        RAW=`./t2 ./test W 1 | grep -E 'new order|^Time' | sed 's/.*= *//g'`
        ### XXX: RESULT NEEDS TO BE MULTIPLIED BY 60 TO GET TPMC
        echo "$1,$W,"`echo $RAW | sed 's/ /,/g'` | tee -a $BENCH/results/tpcc/hstore.csv
      done
    done
  }
  comp tck; bench 'HStoreFixed'
  comp vldb2007; bench 'HStoreOriginal'
  rm -rf $BENCH/systems/tpcc/hstore/test
;;
# ------------------------------------------------------------------------------
mysql)
  for f in /etc/my.cnf /etc/my.ini; do if [ -z "$MY_INI" -a -f "$f" ]; then MY_INI=$f; fi; done
  if [ -z "`grep max_heap_table_size $MY_INI`" ]; then echo "set max_heap_table_size=10G in $MY_INI" && exit 1; fi
  run() {
    ./t2 mysql $myargs <<EOF
SET @res = 0;
CALL exec($MYLOOPS, $1, @res);
SELECT @res;
EOF
  }
  bench() {
    cd "$BENCH";
    for W in $WARES; do
      i=0; while [ "$i" != "$SAMPLES" ]; do i="`expr $i + 1`";
        load $W $1
        OUT=`run $W`
        echo "$2,$W,"`echo $OUT | sed 's/[^0-9=.]//g' | sed 's/=/,/g'` | tee -a $BENCH/results/tpcc/mysql.csv
      done
    done
  }
  bench innodb MySQLInnoDB
  bench memory MySQLMemory
;;
# ------------------------------------------------------------------------------
voltdb)
  #pid="$BENCH/server_pid"
  dep="$BENCH/systems/tpcc/voltdb/deployment.xml"
  cat>$dep<<EOF
  <deployment>
    <cluster hostcount="1" sitesperhost="1" kfactor="0" />
    <commandlog enabled="false"/>
    <!--
    <httpd enabled="true">
        <jsonapi enabled="true" />
    </httpd>
    -->
</deployment>
EOF
  cd $VOLTDB/tests/test_apps/tpcc
  for W in $WARES; do
    i=0; while [ "$i" != "$SAMPLES" ]; do i="`expr $i + 1`";
      # wake server
      $VOLTDB/bin/voltdb create -d $dep -l $VOLTDB/voltdb/license.xml -H localhost tpcc.jar &
      PID="$!"
      # run client
      OUT=`WAREHOUSES=$W DURATION=$VTIME ./run.sh client | grep "New Order:.*txn/m" | awk '{print $7}'`
      echo "VoltDB,$W,$OUT" | tee -a $BENCH/results/tpcc/voltdb.csv
      # shutdown server
      PIDS="`ps -f | grep $PID | cut -d ' ' -f 2,3`"
      kill $PIDS 2>/dev/null; sleep 1
    done
  done
  rm -rf $dep
;;
# ------------------------------------------------------------------------------
load) load $2 innodb;;
# ------------------------------------------------------------------------------
-1|1|2|3|4|5|6)
  for W in $WARES; do
    load $W innodb
    cd $BASE
    sbt compile
    sbt test:compile
    CP="$HOME/.sbt/boot/scala-2.10.2/lib/scala-library.jar:target/scala-2.10/classes:target/scala-2.10/test-classes:lib/dbtlib.jar:lib/log4j-api-2.0-beta9.jar:lib/log4j-core-2.0-beta9.jar:lib/log4j-slf4j-impl-2.0-beta9.jar:lib/mysql-connector-java-5.1.26-bin.jar:lib/slf4j-api-1.7.2.jar:lib/slf4j-ext-1.7.2.jar"
    OUT_FILE="$BENCH/results/tpcc/sstore_"$1"_"$W"_60exec.txt"
    eval "$JAVA_HOME/bin/java -server -Xss512m -Xmx12G -Xms8G -XX:-DontCompileHugeMethods -classpath $CP ddbt.tpcc.tx.TpccInMem -w $W -i $1 -t 60 | tee -a $OUT_FILE"
    eval "$BENCH/tpcc_process.sh"
  done
;;
# ------------------------------------------------------------------------------
*)
  echo "Usage: `basename $0` hstore|mysql|voltdb|-1|1|2|3|4|5|6"
;;
esac
rm -rf $BENCH/t2
